const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(Number(n)||0),val=id=>Number($(id)?.value||0);
const progressive=(income,brackets)=>{let tax=0,prev=0;for(const[cap,rate]of brackets){tax+=Math.max(Math.min(income,cap)-prev,0)*rate;if(income<=cap)break;prev=cap}return Math.max(tax,0)};
const rateAt=(income,brackets)=>{for(const[cap,rate]of brackets)if(income<=cap)return rate;return brackets.at(-1)[1]};
const usBrackets={single:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]],married_joint:[[24800,.10],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]],married_separate:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[384350,.35],[Infinity,.37]],head:[[17700,.10],[67450,.12],[105700,.22],[201750,.24],[256200,.32],[640600,.35],[Infinity,.37]]};
const usStd={single:16100,married_joint:32200,married_separate:16100,head:24150};
const caFederal=[[58523,.14],[117045,.205],[181440,.26],[258482,.29],[Infinity,.33]];
const caProv={AB:[[61200,.08],[154259,.10],[185111,.12],[246813,.13],[370220,.14],[Infinity,.15]],BC:[[50363,.056],[100728,.077],[115648,.105],[140430,.1229],[190405,.147],[265545,.168],[Infinity,.205]],MB:[[47564,.108],[101200,.1275],[Infinity,.174]],NB:[[52333,.094],[104666,.14],[193861,.16],[Infinity,.195]],NL:[[44678,.087],[89354,.145],[159528,.158],[223340,.178],[285319,.198],[570638,.208],[1141275,.213],[Infinity,.218]],NS:[[30995,.0879],[61991,.1495],[97417,.1667],[157124,.175],[Infinity,.21]],NT:[[53003,.059],[106009,.086],[172346,.122],[Infinity,.1405]],NU:[[55801,.04],[111602,.07],[181439,.09],[Infinity,.115]],ON:[[53891,.0505],[107785,.0915],[150000,.1116],[220000,.1216],[Infinity,.1316]],PE:[[33928,.095],[65820,.1347],[106890,.166],[142520,.1762],[200000,.19],[Infinity,.20]],SK:[[54532,.105],[155805,.125],[Infinity,.145]],YT:[[58523,.064],[117045,.09],[181440,.109],[500000,.128],[Infinity,.15]]};
const provBPA={AB:22769,BC:13216,NB:13664,NL:15000,NS:11932,NT:18198,NU:19659,ON:12989,PE:15000,SK:20381};
const usRegions=['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'],caRegions=Object.keys(caProv);
let mode='personal',lastResult=null,scenarioA=null;
function federalBPA(income){if(income<=181440)return 16452;if(income>=258482)return 14829;return 16452-(income-181440)/(258482-181440)*(16452-14829)}
function caPayroll(wages,prov){if(wages<=0||prov==='QC')return{cpp:0,ei:0,total:0,supported:prov!=='QC'};const cpp1=Math.min(Math.max(wages-3500,0),71100)*.0595;const cpp2=Math.min(Math.max(wages-74600,0),10400)*.04;const ei=Math.min(wages,68900)*.0163;return{cpp:cpp1+cpp2,ei,total:cpp1+cpp2+ei,supported:true}}
function caFederalTax(taxable,wages){let tax=progressive(taxable,caFederal);const bpa=federalBPA(taxable);const cea=Math.min(wages,1501);tax-=bpa*.14;tax-=cea*.14;return Math.max(tax,0)}
function caProvinceTax(taxable,prov){if(!prov||!caProv[prov])return 0;let tax=progressive(taxable,caProv[prov]);if(provBPA[prov])tax-=provBPA[prov]*caProv[prov][0][1];return Math.max(tax,0)}
function setError(m=''){const b=$('errorBox');b.textContent=m;b.classList.toggle('hidden',!m);if(m)b.scrollIntoView({behavior:'smooth',block:'center'})}
function populateRegions(){const c=$('country').value,s=$('subRegion');s.innerHTML='<option value="">Select '+(c==='us'?'state':'province / territory')+'</option>';for(const r of(c==='us'?usRegions:caRegions)){const o=document.createElement('option');o.value=r;o.textContent=r;s.appendChild(o)}updateCountryUI()}
function updateBusinessTypes(){const c=$('country').value,s=$('businessType');s.innerHTML='';const list=c==='us'?[['sole','Sole proprietorship'],['partnership','Partnership'],['llc','LLC / pass-through'],['s_corp','S corporation'],['c_corp','C corporation']]:[['sole','Sole proprietorship'],['partnership','Partnership'],['corp_general','Corporation — general federal rate']];for(const[v,t]of list){const o=document.createElement('option');o.value=v;o.textContent=t;s.appendChild(o)}updateBusinessScope()}
function updateCountryUI(){const ca=$('country').value==='ca';$('filingWrap').classList.toggle('hidden',ca);$('canadaPersonalNote').classList.toggle('hidden',!ca);$('usDeductionArea').classList.toggle('hidden',ca);$('caDeductionArea').classList.toggle('hidden',!ca);$('regionNote').textContent=ca?'2026 Canadian federal + selected provincial/territorial brackets are supported. CPP/EI cash flow is supported for non-Quebec employment-only payroll situations.':'2026 US federal ordinary-income brackets and standard deductions are supported. State tax and employee payroll withholding are outside scope.';updateBusinessTypes()}
function updateBusinessScope(){const c=$('country').value,t=$('businessType').value;$('businessScopeNote').textContent=c==='us'&&t==='c_corp'?'US C corporation: 21% federal corporate rate; state corporate tax excluded.':c==='ca'&&t==='corp_general'?'Canadian corporation: 15% general federal corporate rate; provincial corporate tax and SBD excluded.':'Pass-through entity: net business income is calculated, but no fake entity-level flat tax is applied.'}
function switchMode(next){mode=next;const p=next==='personal';$('personalForm').classList.toggle('hidden',!p);$('businessForm').classList.toggle('hidden',p);$('personalBtn').classList.toggle('active',p);$('businessBtn').classList.toggle('active',!p);$('resultsPanel').classList.add('hidden');$('planningPanel').classList.add('hidden');setError('')}
function validate(root){for(const el of root.querySelectorAll('input[type=number]'))if(Number(el.value)<0)return `${el.previousElementSibling?.textContent||'Numeric field'} cannot be negative.`;return ''}
function usSeTax(se){if(se<=0)return 0;const net=se*.9235;return Math.min(net,184500)*.124+net*.029}
function completeness(items){const ok=items.filter(x=>x[0]).length,total=items.length;return total?Math.round(ok/total*100):0}
function calculatePersonal(silent=false){setError('');const bad=validate($('personalForm'));if(bad){if(!silent)setError(bad);return null}if(val('dividends')>0||val('capitalGains')>0){if(!silent)setError('Dividend and capital-gain taxation requires dedicated rules. Set those fields to 0 for this estimate.');return null}const c=$('country').value,w=val('wages'),se=val('selfEmployment'),total=w+val('interest')+se+val('rentalIncome')+val('retirement')+val('otherIncome');let deductions=0,federal=0,region=0,payroll=0,note='',inc=[],marginal=0;if(c==='us'){const status=$('filingStatus').value;if($('standardDeduction').checked)deductions=usStd[status];else deductions=val('mortgageInterest')+Math.min(val('propertyTax'),10000)+val('charitableDonations')+Math.max(val('medicalExpenses')-total*.075,0);deductions+=val('retirementContrib')+val('hsaContrib');const setax=usSeTax(se);deductions+=setax/2;const taxable=Math.max(total-deductions,0);federal=progressive(taxable,usBrackets[status])+setax;marginal=rateAt(taxable,usBrackets[status])*100;note='Federal ordinary-income tax plus estimated self-employment tax where applicable. State tax and employee FICA withholding are excluded.';inc=[[true,'2026 federal brackets'],[true,'2026 standard/itemized deduction'],[true,'Self-employment tax when applicable'],[false,'State income tax'],[false,'Employee FICA withholding'],[false,'Capital gains / qualified dividends'],[false,'2026 special deduction eligibility (tips, overtime, seniors, auto interest)']];return makeResult(total,deductions,taxable,federal,region,payroll,marginal,note,inc,silent)}else{deductions=val('rrspContrib');const taxable=Math.max(total-deductions,0),prov=$('subRegion').value;federal=caFederalTax(taxable,w);region=caProvinceTax(taxable,prov);const p=caPayroll(w,prov);payroll=p.total;marginal=(rateAt(taxable,caFederal)+(prov&&caProv[prov]?rateAt(taxable,caProv[prov]):0))*100;note='Federal/provincial bracket tax includes the federal basic personal credit, Canada Employment Amount, and selected provincial BPA credits where available. CPP/EI are shown as cash-flow deductions, not income tax.';inc=[[true,'2026 federal brackets'],[true,'Federal basic personal credit'],[true,'Canada Employment Amount'],[true,'RRSP deduction'],[!!prov,'Province/territory selected'],[!!provBPA[prov],provBPA[prov]?`${prov} basic personal credit`:'Province-specific BPA not modeled'],[p.supported,'CPP/CPP2 + EI payroll contribution'],[false,'CPP coordination for mixed employment + self-employment'],[false,'Many other federal/provincial credits & surtaxes'],[false,'Capital gains / dividend gross-up rules']];return makeResult(total,deductions,taxable,federal,region,payroll,marginal,note,inc,silent)}}
function calculateBusiness(silent=false){setError('');const bad=validate($('businessForm'));if(bad){if(!silent)setError(bad);return null}const gross=val('grossReceipts'),returns=val('returnsAllowances');if(returns>gross){if(!silent)setError('Returns & allowances cannot exceed gross receipts.');return null}const avail=val('beginningInventory')+val('purchases')+val('laborCosts');if(val('endingInventory')>avail){if(!silent)setError('Ending inventory cannot exceed beginning inventory + purchases + direct labor.');return null}const cogs=avail-val('endingInventory'),ids=['advertising','vehicleExpenses','officeExpenses','rentLease','utilities','insurance','professionalFees','employeeWages','repairs','travel','depreciation','businessInterest','otherExpenses','homeOffice'],expenses=ids.reduce((s,id)=>s+val(id),0),revenue=gross-returns+val('otherBusinessIncome'),net=revenue-cogs-expenses,c=$('country').value,t=$('businessType').value;let federal=0,note='',inc=[];if(c==='us'&&t==='c_corp'){federal=Math.max(net,0)*.21;note='US C-corporation federal income tax only.';inc=[[true,'21% federal C-corp rate'],[false,'State corporate tax'],[false,'Corporate credits/special provisions']]}else if(c==='ca'&&t==='corp_general'){federal=Math.max(net,0)*.15;note='Canadian general federal corporate tax only.';inc=[[true,'15% general federal corporate rate'],[false,'Provincial corporate tax'],[false,'Small-business deduction eligibility']]}else{note='Pass-through entity: net business income shown; owner-level tax not included here.';inc=[[true,'Revenue, COGS and entered expenses'],[false,'Owner-level personal tax'],[false,'Entity-specific special rules']]}return makeResult(revenue,cogs+expenses,Math.max(net,0),federal,0,0,0,note,inc,silent)}
function makeResult(total,deductions,taxable,federal,region,payroll,marginal,note,inc,silent){const estimated=Math.max(federal+region,0),after=total-estimated-payroll,score=completeness(inc),r={timestamp:new Date().toISOString(),country:$('country').value,subRegion:$('subRegion').value,mode,total,deductions,taxable,federal,regionTax:region,payroll,estimated,effective:total>0?estimated/total*100:0,marginal,after,monthly:after/12,note,inc,score};if(!silent)renderResult(r);return r}
function renderResult(r){lastResult=r;$('estimatedTax').textContent=money(r.estimated);$('marginalRate').textContent=r.marginal.toFixed(1)+'%';$('afterTax').textContent=money(r.after);$('monthlyTakeHome').textContent=money(r.monthly);$('totalIncome').textContent=money(r.total);$('totalDeductions').textContent=money(r.deductions);$('taxableIncome').textContent=money(r.taxable);$('federalTax').textContent=money(r.federal);$('subRegionTax').textContent=money(r.regionTax);$('payrollTax').textContent=money(r.payroll);$('effectiveRate').textContent=r.effective.toFixed(1)+'%';$('regionTaxLabel').textContent=r.country==='ca'?'Province / territory tax':'State tax';$('resultNote').textContent=r.note;$('assumptions').replaceChildren(...r.inc.map(([ok,t])=>{const el=document.createElement('div');el.className='assumption '+(ok?'ok':'no');el.textContent=(ok?'✓':'!')+' '+String(t);return el}));$('scoreRing').style.setProperty('--pct',r.score+'%');$('scoreValue').textContent=r.score+'%';$('scoreText').textContent=r.score>=75?'Strong directional estimate for the supported inputs.':'Several material rules are outside the model; treat this as directional.';$('resultsPanel').classList.remove('hidden');$('liveEstimate').textContent=money(r.estimated);$('liveMarginal').textContent=r.marginal.toFixed(1)+'%';$('liveMonthly').textContent=money(r.monthly);$('liveScore').textContent=r.score+'%';$('liveStatus').textContent='Calculated with explicit 2026 scope. Review excluded assumptions before making a financial decision.';renderPlanning(r);$('resultsPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function renderPlanning(r){const caPersonal=r.country==='ca'&&r.mode==='personal';$('planningPanel').classList.toggle('hidden',!caPersonal);if(!caPersonal)return;$('rrspCard').classList.remove('hidden');updateRrsp();const list=Object.entries(caProv).map(([p,b])=>({p,t:progressive(r.taxable,b)})).sort((a,b)=>a.t-b.t).slice(0,6);$('provinceList').innerHTML=list.map(x=>`<div class="province-row"><span>${x.p}</span><strong>${money(x.t)}</strong></div>`).join('')}
function updateRrsp(){if(!lastResult||lastResult.country!=='ca'||lastResult.mode!=='personal')return;const extra=val('rrspWhatIf'),taxable=Math.max(lastResult.taxable-extra,0),prov=lastResult.subRegion,newTax=caFederalTax(taxable,val('wages'))+caProvinceTax(taxable,prov),savings=Math.max(lastResult.estimated-newTax,0);$('rrspSavings').textContent=money(savings)}
function currentCalc(s=false){return mode==='personal'?calculatePersonal(s):calculateBusiness(s)}
function saveScenario(){const r=currentCalc(true);if(!r){setError('Complete a valid supported scenario before saving Scenario A.');return}scenarioA=structuredClone(r);$('saveScenarioBtn').textContent='✓ Scenario A saved'}
function compare(){if(!scenarioA){setError('Save Scenario A first.');return}const b=lastResult||currentCalc(true);if(!b)return;const card=r=>`<div class="break-row"><span>Tax</span><strong>${money(r.estimated)}</strong></div><div class="break-row"><span>Monthly take-home</span><strong>${money(r.monthly)}</strong></div><div class="break-row"><span>Marginal rate</span><strong>${r.marginal.toFixed(1)}%</strong></div>`;$('scenarioA').innerHTML=card(scenarioA);$('scenarioB').innerHTML=card(b);const d=b.after-scenarioA.after;$('scenarioDelta').className='scenario-delta '+(d>=0?'positive':'negative');$('scenarioDelta').textContent=d===0?'No estimated after-tax difference.':`Current scenario has ${money(Math.abs(d))} ${d>0?'more':'less'} annual after-tax cash flow than Scenario A.`;$('comparePanel').classList.remove('hidden')}
function readSaved(){try{const a=JSON.parse(localStorage.getItem('taxmetric_saved')||'[]');return Array.isArray(a)?a.filter(r=>r&&typeof r==='object').slice(-100):[]}catch{return[]}}
function writeSaved(a){try{localStorage.setItem('taxmetric_saved',JSON.stringify(a.slice(-100)));renderSaved()}catch{setError('Browser storage is unavailable.')}}
function renderSaved(){
 const box=$('savedCalculations'),a=readSaved();box.replaceChildren();
 if(!a.length){const empty=document.createElement('p');empty.className='panel-desc';empty.textContent='No saved calculations yet.';box.append(empty);return;}
 a.slice().reverse().forEach((r,i)=>{
  const idx=a.length-1-i,el=document.createElement('div'),content=document.createElement('div'),title=document.createElement('strong'),summary=document.createElement('span'),del=document.createElement('button');
  el.className='saved-item';title.textContent=`${String(r.country||'').toUpperCase()} ${String(r.subRegion||'')} · ${String(r.mode||'')}`;
  summary.textContent=`${new Date(r.timestamp).toLocaleString()} · Tax ${money(Number(r.estimated)||0)} · Take-home ${money(Number(r.after)||0)}`;
  del.className='btn danger';del.textContent='Delete';del.dataset.del=String(idx);del.onclick=()=>{const saved=readSaved();saved.splice(idx,1);writeSaved(saved)};
  content.append(title,summary);el.append(content,del);box.append(el);
 });
}
document.querySelectorAll('.step').forEach(b=>b.onclick=()=>$(b.dataset.target)?.scrollIntoView({behavior:'smooth'}));$('country').onchange=populateRegions;$('businessType').onchange=updateBusinessScope;$('personalBtn').onclick=()=>switchMode('personal');$('businessBtn').onclick=()=>switchMode('business');$('standardDeduction').onchange=e=>$('itemizedSection').classList.toggle('hidden',e.target.checked);$('calculateBtn').onclick=()=>currentCalc(false);$('saveScenarioBtn').onclick=saveScenario;$('compareBtn').onclick=compare;$('rrspWhatIf').oninput=updateRrsp;$('saveBtn').onclick=()=>{if(!lastResult)return;const a=readSaved();a.push(lastResult);writeSaved(a)};$('clearSavedBtn').onclick=()=>{localStorage.removeItem('taxmetric_saved');renderSaved()};$('methodBtn').onclick=()=>$('methodModal').classList.remove('hidden');$('closeMethod').onclick=()=>$('methodModal').classList.add('hidden');$('methodModal').onclick=e=>{if(e.target===$('methodModal'))$('methodModal').classList.add('hidden')};populateRegions();switchMode('personal');renderSaved();
