const progressive=(income,brackets)=>{let tax=0,prev=0;for(const[cap,rate]of brackets){tax+=Math.max(Math.min(income,cap)-prev,0)*rate;if(income<=cap)break;prev=cap}return Math.max(tax,0)};
const rateAt=(income,brackets)=>{for(const[cap,rate]of brackets)if(income<=cap)return rate;return brackets.at(-1)[1]};
const usBrackets={single:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]],married_joint:[[24800,.10],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]],married_separate:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[384350,.35],[Infinity,.37]],head:[[17700,.10],[67450,.12],[105700,.22],[201750,.24],[256200,.32],[640600,.35],[Infinity,.37]]};
const usStd={single:16100,married_joint:32200,married_separate:16100,head:24150};
const caFederal=[[58523,.14],[117045,.205],[181440,.26],[258482,.29],[Infinity,.33]];
const caProv={AB:[[61200,.08],[154259,.10],[185111,.12],[246813,.13],[370220,.14],[Infinity,.15]],BC:[[50363,.056],[100728,.077],[115648,.105],[140430,.1229],[190405,.147],[265545,.168],[Infinity,.205]],MB:[[47564,.108],[101200,.1275],[Infinity,.174]],NB:[[52333,.094],[104666,.14],[193861,.16],[Infinity,.195]],NL:[[44678,.087],[89354,.145],[159528,.158],[223340,.178],[285319,.198],[570638,.208],[1141275,.213],[Infinity,.218]],NS:[[30995,.0879],[61991,.1495],[97417,.1667],[157124,.175],[Infinity,.21]],NT:[[53003,.059],[106009,.086],[172346,.122],[Infinity,.1405]],NU:[[55801,.04],[111602,.07],[181439,.09],[Infinity,.115]],ON:[[53891,.0505],[107785,.0915],[150000,.1116],[220000,.1216],[Infinity,.1316]],PE:[[33928,.095],[65820,.1347],[106890,.166],[142520,.1762],[200000,.19],[Infinity,.20]],SK:[[54532,.105],[155805,.125],[Infinity,.145]],YT:[[58523,.064],[117045,.09],[181440,.109],[500000,.128],[Infinity,.15]]};
const provBPA={AB:22769,BC:13216,NB:13664,NL:15000,NS:11932,NT:18198,NU:19659,ON:12989,PE:15000,SK:20381};
const usRegions=['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'],caRegions=Object.keys(caProv);

function federalBPA(income){if(income<=181440)return 16452;if(income>=258482)return 14829;return 16452-(income-181440)/(258482-181440)*(16452-14829)}
function caPayroll(wages,prov){if(wages<=0||prov==='QC')return{cpp:0,ei:0,total:0,supported:prov!=='QC'};const cpp1=Math.min(Math.max(wages-3500,0),71100)*.0595;const cpp2=Math.min(Math.max(wages-74600,0),10400)*.04;const ei=Math.min(wages,68900)*.0163;return{cpp:cpp1+cpp2,ei,total:cpp1+cpp2+ei,supported:true}}
function caFederalTax(taxable,wages){let tax=progressive(taxable,caFederal);const bpa=federalBPA(taxable);const cea=Math.min(wages,1501);tax-=bpa*.14;tax-=cea*.14;return Math.max(tax,0)}
function caProvinceTax(taxable,prov){if(!prov||!caProv[prov])return 0;let tax=progressive(taxable,caProv[prov]);if(provBPA[prov])tax-=provBPA[prov]*caProv[prov][0][1];return Math.max(tax,0)}
function usSeTax(se){if(se<=0)return 0;const net=se*.9235;return Math.min(net,184500)*.124+net*.029}
function completeness(items){const ok=items.filter(x=>x[0]).length,total=items.length;return total?Math.round(ok/total*100):0}
export const numericFields = ["wages", "interest", "selfEmployment", "rentalIncome", "retirement", "otherIncome", "dividends", "capitalGains", "mortgageInterest", "propertyTax", "charitableDonations", "medicalExpenses", "retirementContrib", "hsaContrib", "rrspContrib", "grossReceipts", "returnsAllowances", "otherBusinessIncome", "beginningInventory", "purchases", "laborCosts", "endingInventory", "advertising", "vehicleExpenses", "officeExpenses", "rentLease", "utilities", "insurance", "professionalFees", "employeeWages", "repairs", "travel", "depreciation", "businessInterest", "otherExpenses", "homeOffice", "rrspWhatIf"];
export function normalizeInput(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('A scenario object is required.');
 const {country='us',mode='personal',subRegion='',filingStatus='single',businessType='sole',standardDeduction=true}=raw;
 if(!['us','ca'].includes(country)||!['personal','business'].includes(mode))throw new Error('Invalid country or calculation mode.');
 if(subRegion&&!(country==='us'?usRegions:caRegions).includes(subRegion))throw new Error('Unsupported state or province.');
 if(!Object.hasOwn(usBrackets,filingStatus))throw new Error('Invalid filing status.');
 if(!(country==='us'?['sole','partnership','llc','s_corp','c_corp']:['sole','partnership','corp_general']).includes(businessType))throw new Error('Invalid business type.');
 if(typeof standardDeduction!=='boolean')throw new Error('Standard deduction must be a boolean.');
 const input={country,mode,subRegion,filingStatus,businessType,standardDeduction};
 for(const field of numericFields){const n=raw[field]??0;if(typeof n==='number'&&n<0)throw new Error(`${field} cannot be negative.`);if(typeof n!=='number'||!Number.isFinite(n)||n>1e9)throw new Error(`${field} must be a finite nonnegative number at most 1 billion.`);input[field]=n;}
 if(mode==='personal'&&(input.dividends>0||input.capitalGains>0))throw new Error('Dividend and capital-gain taxation requires dedicated rules.');
 return input;
}
export function calculate(raw){
 const input=normalizeInput(raw),mode=input.mode;
 const val=id=>input[id]??0;
 const $=id=>({value:input[id],checked:input[id]});
 const makeResult=(total,deductions,taxable,federal,region,payroll,marginal,note,inc)=>{
  const estimated=Math.max(federal+region,0),after=total-estimated-payroll;
  return {timestamp:new Date().toISOString(),country:input.country,subRegion:input.subRegion,mode,total,deductions,taxable,federal,regionTax:region,payroll,estimated,effective:total>0?estimated/total*100:0,marginal,after,monthly:after/12,note,inc,score:completeness(inc),modelVersion:'2026-v1'};
 };
 const silent=true;
 if(mode==='personal'){const c=$('country').value,w=val('wages'),se=val('selfEmployment'),total=w+val('interest')+se+val('rentalIncome')+val('retirement')+val('otherIncome');let deductions=0,federal=0,region=0,payroll=0,note='',inc=[],marginal=0;if(c==='us'){const status=$('filingStatus').value;if($('standardDeduction').checked)deductions=usStd[status];else deductions=val('mortgageInterest')+Math.min(val('propertyTax'),10000)+val('charitableDonations')+Math.max(val('medicalExpenses')-total*.075,0);deductions+=val('retirementContrib')+val('hsaContrib');const setax=usSeTax(se);deductions+=setax/2;const taxable=Math.max(total-deductions,0);federal=progressive(taxable,usBrackets[status])+setax;marginal=rateAt(taxable,usBrackets[status])*100;note='Federal ordinary-income tax plus estimated self-employment tax where applicable. State tax and employee FICA withholding are excluded.';inc=[[true,'2026 federal brackets'],[true,'2026 standard/itemized deduction'],[true,'Self-employment tax when applicable'],[false,'State income tax'],[false,'Employee FICA withholding'],[false,'Capital gains / qualified dividends'],[false,'2026 special deduction eligibility (tips, overtime, seniors, auto interest)']];return makeResult(total,deductions,taxable,federal,region,payroll,marginal,note,inc,silent)}else{deductions=val('rrspContrib');const taxable=Math.max(total-deductions,0),prov=$('subRegion').value;federal=caFederalTax(taxable,w);region=caProvinceTax(taxable,prov);const p=caPayroll(w,prov);payroll=p.total;marginal=(rateAt(taxable,caFederal)+(prov&&caProv[prov]?rateAt(taxable,caProv[prov]):0))*100;note='Federal/provincial bracket tax includes the federal basic personal credit, Canada Employment Amount, and selected provincial BPA credits where available. CPP/EI are shown as cash-flow deductions, not income tax.';inc=[[true,'2026 federal brackets'],[true,'Federal basic personal credit'],[true,'Canada Employment Amount'],[true,'RRSP deduction'],[!!prov,'Province/territory selected'],[!!provBPA[prov],provBPA[prov]?`${prov} basic personal credit`:'Province-specific BPA not modeled'],[p.supported,'CPP/CPP2 + EI payroll contribution'],[false,'CPP coordination for mixed employment + self-employment'],[false,'Many other federal/provincial credits & surtaxes'],[false,'Capital gains / dividend gross-up rules']];return makeResult(total,deductions,taxable,federal,region,payroll,marginal,note,inc,silent)}}
 else{const gross=val('grossReceipts'),returns=val('returnsAllowances');if(returns>gross){throw new Error('Returns & allowances cannot exceed gross receipts.')}const avail=val('beginningInventory')+val('purchases')+val('laborCosts');if(val('endingInventory')>avail){throw new Error('Ending inventory cannot exceed beginning inventory + purchases + direct labor.')}const cogs=avail-val('endingInventory'),ids=['advertising','vehicleExpenses','officeExpenses','rentLease','utilities','insurance','professionalFees','employeeWages','repairs','travel','depreciation','businessInterest','otherExpenses','homeOffice'],expenses=ids.reduce((s,id)=>s+val(id),0),revenue=gross-returns+val('otherBusinessIncome'),net=revenue-cogs-expenses,c=$('country').value,t=$('businessType').value;let federal=0,note='',inc=[];if(c==='us'&&t==='c_corp'){federal=Math.max(net,0)*.21;note='US C-corporation federal income tax only.';inc=[[true,'21% federal C-corp rate'],[false,'State corporate tax'],[false,'Corporate credits/special provisions']]}else if(c==='ca'&&t==='corp_general'){federal=Math.max(net,0)*.15;note='Canadian general federal corporate tax only.';inc=[[true,'15% general federal corporate rate'],[false,'Provincial corporate tax'],[false,'Small-business deduction eligibility']]}else{note='Pass-through entity: net business income shown; owner-level tax not included here.';inc=[[true,'Revenue, COGS and entered expenses'],[false,'Owner-level personal tax'],[false,'Entity-specific special rules']]}return makeResult(revenue,cogs+expenses,Math.max(net,0),federal,0,0,0,note,inc,silent)}
}
